# Author(s): Geromy Cunningham
# Purpose: Check if formatting is correct on a push to any branch

name: Format

on:
  push:
    branches-ignore: ["main"]
    
permissions:
   contents: read
   statuses: write

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: clang-format check
        uses: jidicula/clang-format-action@v4.14.0
        with:
          clang-format-version: "17"
          check-path: "src/**"